version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: chat-app-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/chatapp}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - NODE_ENV=production
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME:-your_cloud_name}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY:-your_api_key}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET:-your_api_secret}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend service
  frontend:
    build: ./frontend
    container_name: chat-app-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: chat-app-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: